# -*- coding: utf-8 -*-
"""Img_to_txt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tlrg4eE7x5kSdj5WxySW2_02XlH5I3O6
"""

!sudo apt-get install tesseract-ocr
!pip install tesseract
!pip install opencv-python

import pytesseract
from google.colab.patches import cv2_imshow
import cv2

from google.colab import files
uploaded=files.upload()

for fn in uploaded.keys():
  img_path=fn

img=cv2.imread(img_path)
cv2_imshow(img)

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

text=pytesseract.image_to_string(gray)

print("Extracted text: ")
print(text)



